title: Matteo Spadetto

theme: jekyll-theme-minimal

logo: that_is_me.jpg

description: "Postdoc at Gallinette, LS2N of the University of Nantes, France, supervised by Guilhem Jaber.<br><br>Email address. Contact me at <em>matteo.nomen.42@gmail.com</em> where nomen is spadetto."
