title: Matteo Spadetto

theme: jekyll-theme-minimal

logo: that_is_me.jpg

description: "Postdoc at the Functional Programming Lab, School of Computer Science of the University of Nottingham, UK, supervised by Nicolai Kraus.<br><br>Email address. Contact me at <em>matteo.nomen.42@gmail.com</em> where nomen is spadetto."
