title: Matteo Spadetto

theme: jekyll-theme-minimal

description: "Postdoc at the LS2N of the University of Nantes, France, supervised by Guilhem Jaber.<br><br>Previusly, I was a postdoc at the Dipartimento di Scienze Matematiche, Informatiche e Fisiche of the University of Udine, Italy, supervised by Marino Miculan.<br><br>My PhD thesis, completed at the School of Mathematics of the University of Leeds (UK), is in mathematical logic, dependent type theory, and categorical semantics. It was supervised by Nicola Gambino, <a href='https://lipn.univ-paris13.fr/~olimpieri/'>Federico Olimpieri</a>, and Michael Rathjen.<br><br>Email address. Contact me at <em>matteo.nomen.42@gmail.com</em> where nomen is spadetto."

